function Main_GUI

    hs.main_fig = figure('ToolBar',      'none', ...
                        'MenuBar',      'none', ...
                        'NumberTitle',  'off', ...
                        'Name',         'DATABASE Updater', ...
                        'Color',        'white', ...
                        'Resize',       'off', ...
                        'Position',     [400,400,330,165], ...  
                        'Visible',      'off');  % make it invisible at the beginning
        
    hs.run_bttn    = uicontrol('Style',             'pushbutton', ...
                               'String',            'Update', ...
                               'Position',          [10,15,50,25]);
                        
    hs.manual_bttn = uicontrol('Style',             'togglebutton', ...
                               'String',            'Manual', ...
                               'Max',               1, ...
                               'Min',               0, ...
                               'Value',             1, ...
                               'Position',          [70,15,50,25]);

    hs.start_text = uicontrol('Style',              'text', ...
                              'String',             'From:', ...
                              'BackgroundColor',    'white', ...
                              'Enable',             'off', ...
                              'Position',           [130,20,40,15]);    

    hs.end_text   = uicontrol('Style',              'text', ...
                              'String',             'To:', ...
                              'BackgroundColor',    'white', ...
                              'Enable',             'off', ...
                              'Position',           [230,20,30,15]);    
                        
    hs.start_edit = uicontrol('Style',              'edit', ...
                              'String',             getcfgdata('start_date'), ...
                              'BackgroundColor',    'white', ...
                              'Enable',             'off', ...
                              'Position',           [170,15,60,25]);    

    hs.end_edit   = uicontrol('Style',              'edit', ...
                              'String',             getcfgdata('end_date'), ...
                              'BackgroundColor',    'white', ...
                              'Enable',             'off', ...
                              'Position',           [260,15,60,25]);
    
	hs.dateUpdate_bttn  = uicontrol('Style',        'pushbutton', ...
                               'String',            'Update 1', ...
                               'Position',          [10,70,50,25]);   
	
	hs.dateUpdate_text = uicontrol('Style',         'text', ...
                              'String',             '1. Update All Trade Date List', ...
                              'FontName',           'Tahoma', ...
                              'FontWeight',         'bold', ...
                              'HorizontalAlignment','left', ...
                              'BackgroundColor',    'white', ...
                              'Enable',             'on', ...
                              'Position',           [70,70,190,15]); 
                          
    hs.ts_com_status = uicontrol('Style',           'pushbutton', ...
                                 'String',          'TS.COM', ...
                                 'CreateFcn',       {@ts_com}, ...
                                 'Position',        [270, 70, 50, 25]);
                          
    hs.app1_bttn = uicontrol('Style',               'pushbutton', ...
                             'String',              'App1', ...
                             'Position',            [10, 125, 50, 25]);
                       
    hs.app2_bttn = uicontrol('Style',               'pushbutton', ...
                             'String',              'App2', ...
                             'Position',            [70, 125, 50, 25]);                         
                         
    hs.app3_bttn = uicontrol('Style',               'pushbutton', ...
                             'String',              'App3', ...
                             'Position',            [130, 125, 50, 25]);
                         
    hs.app4_bttn = uicontrol('Style',               'pushbutton', ...
                             'String',              'App4', ...
                             'Position',            [190, 125, 50, 25]);
                         
    hs.app4_bttn = uicontrol('Style',               'pushbutton', ...
                             'String',              'App5', ...
                             'Position',            [250, 125, 50, 25]);                         
                         
    % initial...GUI..Data

    
    %
    set(hs.run_bttn, 'Callback', {@run_func, hs});
    set(hs.manual_bttn, 'Callback', {@manual_toggle, hs});
    set(hs.dateUpdate_bttn, 'Callback', {@dateUpdate});
    set(hs.ts_com_status, 'Callback', {@ts_com});  
    set(hs.app1_bttn, 'Callback', {@run_app1});
    
    % Show me!
    set(hs.main_fig, 'Visible', 'on');
    
    % block execution for daemon.
    waitfor(hs.main_fig); 
end


%%
function manual_toggle(hobj, ~, hs)
% Note: togglebutton's Value Property is changed automatically behind by system
% 
    hobj_status = get(hobj, 'Value');
    if hobj_status == 0
        set(hs.start_text, 'Enable', 'on');
        set(hs.end_text, 'Enable', 'on');
        set(hs.start_edit, 'Enable', 'on');
        set(hs.end_edit, 'Enable', 'on');
    else
        set(hs.start_text, 'Enable', 'off');
        set(hs.end_text, 'Enable', 'off');
        set(hs.start_edit, 'Enable', 'off');
        set(hs.end_edit, 'Enable', 'off');
    end
    
end

%%
function run_func(~, ~, hs)

    manual_status = get(hs.manual_bttn, 'Value');
    if manual_status == 1
        setcfgdata('auto_or_manual', 1);
    elseif manual_status == 0
        setcfgdata('auto_or_manual', 0);
        setcfgdata('start_date', get(hs.start_edit, 'String'));
        setcfgdata('end_date', get(hs.end_edit, 'String'));
    end
    
    Main_stocksDQ;
    
end

%%
function dateUpdate(~, ~)
    
    com_obj = get_wsVar('base', 'ts');
    if(~iscom(com_obj))
        error('TinySoft COM Automation Server error!!!');
    end
    all_trade_dates = get_RemoteDateList(com_obj, '20000101', datestr(date, 'yyyymmdd'));
    setcfgdata('all_trade_dates', all_trade_dates);
    fprintf(1, '''all_trade_dates'' updated!'); 
end

%%
function ts_com(hobj, ~)
	tmp_a = evalin('base', 'exist(''ts'', ''var'')');
    if tmp_a == 0
        set(hobj, 'BackgroundColor', 'red');
    else
        set(hobj, 'BackgroundColor', 'green');
    end
end

%%
function run_app1(~, ~)
    Run_App1;
end


